# app1-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-node-app-service
  namespace: default
spec:
  selector:
    app: hello-node-app
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
