# app1-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: text-next-app-service
  namespace: default
spec:
  selector:
    app: text-next-app
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
