apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-node-app
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: manifests/charts/example-node-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      values:
        replicaCount: 1
        image:
          repository: registry.digitalocean.com/dc-containers-test/hello-node-app
          tag: latest
