apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-next-app
  namespace: default
spec:
  replicas: 1
  selector: # This is required for the Deployment to select the appropriate pods
    matchLabels:
      app: text-next-app
  template:
    metadata:
      labels:
        app: text-next-app
    spec:
      imagePullSecrets:
        - name: docr-secret
      containers:
        - name: text-next-app
          image: registry.digitalocean.com/dc-containers-test/text-next-app:latest
          ports:
            - containerPort: 3000
---
# app1-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: text-next-app-service
  namespace: default
spec:
  selector:
    app: text-next-app
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
